name: workflow-services

on:
    push:
        branches:
            - master

jobs: 
  trabajo1: 
    runs-on: ubuntu-latest

    steps: 
      - name: "Checkout del repositorio"
        uses: actions/checkout@v2
      - name: listar archivos
        run: ls -la